/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (GUI_ID_USER + 0x00)
#define ID_GRAPH_0        (GUI_ID_USER + 0x01)
#define ID_TEXT_0        (GUI_ID_USER + 0x02)
#define ID_BUTTON_0        (GUI_ID_USER + 0x03)
#define ID_TEXT_1        (GUI_ID_USER + 0x04)
#define ID_TEXT_2        (GUI_ID_USER + 0x05)
#define ID_SLIDER_0        (GUI_ID_USER + 0x06)
#define ID_SLIDER_1        (GUI_ID_USER + 0x07)
#define ID_BUTTON_1        (GUI_ID_USER + 0x09)
#define ID_BUTTON_2        (GUI_ID_USER + 0x0A)
#define ID_TEXT_3        (GUI_ID_USER + 0x0B)
#define ID_BUTTON_3        (GUI_ID_USER + 0x0C)
#define ID_BUTTON_4        (GUI_ID_USER + 0x0D)
#define ID_BUTTON_5        (GUI_ID_USER + 0x0E)
#define ID_TEXT_4        (GUI_ID_USER + 0x0F)
#define ID_TEXT_5        (GUI_ID_USER + 0x10)
#define ID_TEXT_6        (GUI_ID_USER + 0x11)
#define ID_TEXT_7        (GUI_ID_USER + 0x12)
#define ID_TEXT_8        (GUI_ID_USER + 0x13)

// USER START (Optionally insert additional includes)
// USER END

// USER START (Optionally insert additional defines)
// USER END


/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 7, 4, 800, 480, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 49, 31, 450, 400, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Device data:", ID_TEXT_0, 616, 9, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Get device data", ID_BUTTON_0, 563, 40, 97, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ProdID:", ID_TEXT_1, 666, 35, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Revision:", ID_TEXT_2, 666, 55, 80, 20, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 566, 126, 134, 20, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 566, 195, 134, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Set", ID_BUTTON_1, 710, 98, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Set", ID_BUTTON_2, 710, 136, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Measurement control", ID_TEXT_3, 564, 238, 134, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Start", ID_BUTTON_3, 562, 271, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Stop", ID_BUTTON_4, 664, 272, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Clear", ID_BUTTON_5, 664, 309, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Graph control", ID_TEXT_4, 561, 305, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Last result: [ppm]", ID_TEXT_5, 561, 347, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Info", ID_TEXT_6, 560, 387, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Ref Pressure", ID_TEXT_7, 577, 96, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Measurement rate", ID_TEXT_8, 570, 166, 209, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Get device data'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_1: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Start'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Stop'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Clear'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
